# Generated by Django 4.2.6 on 2023-10-17 06:24

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import social.profiles.profile_photo_api


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        default="profile_default.png",
                        upload_to=social.profiles.profile_photo_api.profile_photo_path,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=300)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, default="", max_length=2, null=True
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("birthday", models.DateField(blank=True)),
            ],
        ),
    ]
