# Generated by Django 4.2.6 on 2023-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
