# Generated by Django 4.2.6 on 2023-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
