# Generated by Django 4.2.7 on 2023-11-16 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("private_message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
