# Generated by Django 4.2.6 on 2023-10-17 06:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gallery"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(
                            2023,
                            10,
                            17,
                            6,
                            24,
                            30,
                            144261,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=500, null=True)),
                ("slug", models.SlugField(blank=True, max_length=600, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="post")),
                ("views", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("ONY", "Only Me"), ("EVN", "Everyone")],
                        default="EVN",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(
                            2023,
                            10,
                            17,
                            6,
                            24,
                            30,
                            142212,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
