# Generated by Django 4.2.6 on 2023-10-17 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_gallery_timestamp_alter_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="timestamp",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 10, 17, 7, 26, 7, 795056, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 10, 17, 7, 26, 7, 793943, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
