name: Tests Runner
on:
    - push
    - pull_request

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-20.04
        env:
            ALLOWED_HOSTS: '*'
            SECRET_KEY: 'a secret to everybody'

        steps:
            -   name: Get the code
                uses: actions/checkout@v2
                with:
                    fetch-depth: 1

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.11'
                    architecture: 'x64'
                    cache: 'pip'
                    cache-dependency-path: 'requirements*.txt'

            -   name: Install packages
                run: |
                    # Postgres dev headers for pg_config
                    # libpq-dev
                    # Graphviz support
                    # python3-dev graphviz libgraphviz-dev
                    sudo apt install \
                    libpq-dev \
                    python3-dev graphviz libgraphviz-dev

            -   name: Install packages
                run: pip install -r requirements.txt -r requirements-dev.txt

#
#            - name: Test it
#                run: make coverage
#
#           - name: Check deploy configuration
#                run: ./manage.py check --deploy --fail-level WARNING
#                env:
#                    DATABASE_URL: 'sqlite://:memory:'
#                    SECRET_KEY: 'zt(6jlr#oquxm2t%ryh#n+-72p^(3knbf&q$5x16#o%1im-s7!'
#                    SECURE_SSL_REDIRECT: 'on'
#
#           - name: Check documentation build
#                run: make -C docs html